### ISSUE TITLE
Roadmap de tradução

### ISSUE THREAD

**Issue by aureliosaraiva** [ember-brasil/website#2]
- [x] Página Inicial @lucasaugustofrontend 
- [x] [getting-started](https://github.com/EmberJSBrasil/ember-guides/tree/master/source/getting-started) https://github.com/ember-brasil/website/issues/1 @danilovaz 
- [ ] [addons-and-dependencies](https://github.com/EmberJSBrasil/ember-guides/tree/master/source/addons-and-dependencies) @angelomachado 
- [ ] [applications](https://github.com/EmberJSBrasil/ember-guides/tree/master/source/guides/applications) @marceloboth
- [ ] [components](https://github.com/EmberJSBrasil/ember-guides/tree/master/source/guides/components) @carloshpdoc
- [ ] [configuring-ember](https://github.com/EmberJSBrasil/ember-guides/tree/master/source/guides/configuring-ember) @melderaldo
- [ ] [contributing/adding-new-features](https://github.com/ember-brasil/website/blob/master/source/guides/contributing/adding-new-features.md) @yanmagale
- [x] [contributing/repositories](https://github.com/ember-brasil/website/blob/master/source/guides/contributing/repositories.md) @rahhrta
- [x] [controllers](https://github.com/EmberJSBrasil/ember-guides/tree/master/source/guides/controllers) @danilovaz 
- [ ] [ember-inspector](https://github.com/EmberJSBrasil/ember-guides/tree/master/source/guides/ember-inspector) @bfmjr
- [x] [glossary](https://github.com/EmberJSBrasil/ember-guides/tree/master/source/guides/glossary) @marceloboth
- [ ] [models](https://github.com/EmberJSBrasil/ember-guides/tree/master/source/guides/models)
- [ ] [object-model](https://github.com/EmberJSBrasil/ember-guides/tree/master/source/guides/object-model) @marcelitocs
- [ ] [routing](https://github.com/EmberJSBrasil/ember-guides/tree/master/source/guides/routing)
- [ ] [templates](https://github.com/EmberJSBrasil/ember-guides/tree/master/source/guides/templates)
- [ ] [testing](https://github.com/EmberJSBrasil/ember-guides/tree/master/source/guides/testing) @danilovaz
- [ ] [tutorial](https://github.com/EmberJSBrasil/ember-guides/tree/master/source/guides/tutorial) @aureliosaraiva

**Comment by aureliosaraiva** [comment]
Tutorial @aureliosaraiva

https://github.com/ember-brasil/website/pull/16

**Comment by aureliosaraiva** [comment]
Getting Started @danilovaz

**Comment by danilovaz** [comment]
Configuring Ember: @melderaldo

**Comment by aureliosaraiva** [comment]
@yanmagale https://github.com/ember-brasil/website/issues/28

**Comment by marcelitocs** [comment]
object-model: @marcelitocs

**Comment by danilovaz** [comment]
Ember-Inspector: @bfmjr

**Comment by danilovaz** [comment]
Testing: @danilovaz

**Comment by aureliosaraiva** [comment]
Galera, houve alteração grande no repositório, todo o conteúdo do Guides foi movido para uma subpasta chamada guides. Isso foi feito para conseguir ter outras páginas no site. Porém que tem tradução em andamento, vai dar conflito.

Por favor, atualizem seus forks seguinte: https://github.com/ember-brasil/website/blob/master/README.md#sincronizando-seu-fork

Se precisarem de algo me avisa.

**Comment by carloshpdoc** [comment]
components: @carloshpdoc

**Comment by danilovaz** [comment]
Contributing/repositories: @rahhrta

**Comment by danilovaz** [comment]
Addons and Dependencies: @angelomachado
